data:
  path: "TranferLearningTimeSeries/data/workable_retail_data.csv"
  group_col: "StockCode"
  target_col: "TotalQuantity"
  date_col: "InvoiceDate"
  smoothed_col: "SmoothedTotalQuantity"
  TimeSeriesName_col: "StockCode"
  prediction_path: "TranferLearningTimeSeries/data/predict_retail_data.csv"  # Specify if prediction is needed

preprocessing:
  replace_outliers: true
  smoothing:
    apply: true
    window_size: 3

model:
  path: "TranferLearningTimeSeries/models/nbeats_model_m4_t3.pt"
  horizon: 72 
  test_forecast_length: 12
  forecast_length: 12
  min_size: 60
  epochs: 5
  input_chunk_length: 40
  output_chunk_length: 12
  img_dim1: 20
  img_dim2: 10
  verbose: true
  device: "cpu"  # Options: "cpu", "gpu", "tpu", "mps"
  pl_trainer_kwargs:
    accelerator: "cpu"
  retrain: false  # Set to true if retraining is required
  scale: true  # Set to true if scaling is applied


output:
  prediction_save_path: "TranferLearningTimeSeries/results/predictions.csv"
  scaler_save_path: "TranferLearningTimeSeries/models/scaler.pkl"  # Path to save the scaler
  fine_tune_model_save_path: "TranferLearningTimeSeries/models/fine_tune_TF.pt"