name: Run main.py on config.yaml update

on:
  push:
    paths:
      - 'TransferLearningForForecasting/configs/config.yaml'

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8' # Set the Python version you need
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          # Caching location
          path: ~/.cache/pip
          # Cache key based on the hash of the requirements.txt file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          # Fallback to use when cache is not found
          restore-keys: |
            ${{ runner.os }}-pip
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r TransferLearningForForecasting/requirements.txt

      - name: Run main.py
        run: python TransferLearningForForecasting/main.py

